AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'config/environments/*'
  - 'bin/*'

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
  - 'spec/features/*'
  - 'spec/features/*/*'
  - 'Guardfile'
  - 'config/routes.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/admin/orders_controller.rb'
    - 'app/controllers/user/orders_controller.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/SymbolArray:
  EnforcedStyle: brackets
