AllCops:
  Exclude:
  - 'db/schema.rb'
  - 'config/environments/*'
  - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false

Layout/ExtraSpacing:
  ForceEqualSignAlignment: true

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
  - 'spec/features/*'
  - 'spec/features/*/*'
  - 'Guardfile'
  - 'config/routes.rb'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
