version: '3.4'

services:
  web:
    build: .
    command: script/start-dev.sh
    volumes:
      - .:/app
      - smc-gems:/gems
      - /app/node_modules
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      DB_DEV: smc-development
      DB_HOST: db
      DB_TEST: smc-test
      DB_USERNAME: postgres

  db:
    image: postgres:11.5
    volumes:
      - smc-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  smc-data:
  smc-gems:
